---
services:
  app:
    image: 'jc21/nginx-proxy-manager:2.11.3' #von 2.10.4
    container_name: nginx-proxy-manager
    restart: always
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # Mysql/Maria connection parameters:
      - PUID='1000'
      - PGID= '1000'
      - DB_MYSQL_HOST=db
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_USER=npm
      - DB_MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - DB_MYSQL_NAME=npm
      # Uncomment this if IPv6 is not enabled on your host
      - DISABLE_IPV6=true
    volumes:
      - ./nginx-proxy-manager/:/data
      - ./nginx-letsencrypt/:/etc/letsencrypt
      - ./nginx-proxy-manager/logo-text-vertical-grey.png/:/app/frontend/images/logo-text-vertical-grey.png
      - ./certbot/:/opt/certbot
    depends_on:
      - db

  db:
    image: 'jc21/mariadb-aria:latest'
    container_name: nginx-proxy-manager-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=npm
      - MYSQL_USER=npm
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - ./nginx-mariadb/mysql:/var/lib/mysql