---
services:
  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    restart: always
    user: 'root' 
    ports:
     - '3000:3000'
    volumes:
      - /mnt/Docker/grafana/config:/etc/grafana
      - /mnt/Docker/grafana/data:/var/lib/grafana
    environment:
      TZ: "Europe/Berlin"
      GF_ROOT_URL: https://grafana.sebastianhanz.de/
