---
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
      - '8090:8080'
    volumes:
      - /mnt/Docker/Stirling-PDF/config:/configs
      - /mnt/Docker/Stirling-PDF/customFiles:/customFiles/
      - /mnt/Docker/Stirling-PDF/tessdata:/usr/share/tessdata #Required for extra OCR languages
    environment:
      - DOCKER_ENABLE_SECURITY=false