---
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf
    restart: unless-stopped
    ports:
      - '8090:8080'
    volumes:
      - /mnt/Docker/Stirling-PDF/trainingData:/usr/share/tesseract-ocr/4.00/tessdata #Required for extra OCR languages
      - /mnt/Docker/Stirling-PDF/config:/configs
      - /mnt/Docker/Stirling-PDF/customFiles:/customFiles/
    environment:
      - DOCKER_ENABLE_SECURITY=false