---
services:
    synapse:
        image: 'matrixdotorg/synapse:latest' # From v1.105.0
        container_name: synapse
        environment:
            - TZ=Europe/Berlin
        restart: unless-stopped
        links:
            - postgres
        volumes:
            # USER-ID of Folder has to be 991
            - '${SYNAPSE_STORAGE}:/data'
        ports:
            - '8008:8008'
            - '4143:443'
        
        depends_on:
        - postgres

    postgres:
        image: 'postgres:alpine3.19'
        container_name: postgres-synapse
        restart: unless-stopped
        volumes:
            - '${POSTGRES_STORAGE}:/var/lib/postgresql/data'
        environment:
            - POSTGRES_INITDB_ARGS=
            - LC_CTYPE=
            - LC_COLLATE=
            - POSTGRES_DB=matrix_synapse
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=matrix