services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.9.9 #from 10.9.8, 10.9.7, 10.8.13 
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - JELLYFIN_PublishedServerUrl=10.0.2.101 #optional
      - DOCKER_MODS=ghcr.io/jumoog/intro-skipper #neuer Intro-Skipper
    volumes:
      - ./:/config
      - ./img:/usr/share/jellyfin/web/assets/img
      - /mnt/NFS/Jellyfin/tvseries:/data/tvshows
      - /mnt/NFS/Jellyfin/movies:/data/movies
      - /mnt/NFS/Jellyfin/music:/data/music
      - /mnt/NFS/Jellyfin/private:/data/private
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri # For H/W transcoding
    restart: unless-stopped