#docker network create -d macvlan -o parent=eth0 \
#  --subnet 10.10.10.0/24 \
#  --gateway 10.10.10.1 \
#  --ip-range 10.10.10.11/30 \
#  --aux-address 'host=10.10.10.12' \
#  MyMacVlan
---
services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguard
    ports:
      - 53:53/tcp
      - 53:53/udp
      #- 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      #- 80:80/tcp
      #- 443:443/tcp
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    restart: unless-stopped