---
services:
  bitwarden:
    container_name: bitwarden
    image: vaultwarden/server:latest
    hostname: ${HOSTNAME}
    restart: always
    ports:
      - 180:80
    environment:
      - ADMIN_TOKEN=${BITWARDEN_ADMIN_TOKEN} #Im Argon2-Format
    volumes:
      - '${BITWARDEN_DATA}:/data:rw'
      - '/mnt/Docker/Bitwarden/custom/bitwarden_banner.png:/web-vault/images/logo-dark@2x.png' #Custom Logo
