---
services:
  bitwarden:
    container_name: bitwarden
    image: vaultwarden/server:1.32.7 # von 1.32.3
    hostname: ${HOSTNAME}
    restart: always
    ports:
      - 180:80
    environment:
      - ADMIN_TOKEN=${BITWARDEN_ADMIN_TOKEN} #Im Argon2-Format
    volumes:
      - './:/data:rw'
      - './custom/bitwarden_banner.png:/web-vault/images/logo-dark@2x.png' #Custom Logo